services:
  - type: web
    name: rawaiti-pehnawa-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dcstsd547
      - key: CLOUDINARY_API_KEY
        value: "314448549271518"
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false